# fly.toml app configuration file generated for empty-morning-9725 on 2023-07-21T14:14:44+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "empty-morning-9725"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
